version: '3'

services:
  api:
    build: ./
    ports:
    - 8080:8080
    environment:
      - PORT=8080
      - DB_CONNECTION_STRING=host=postgres port=5432 user=postgres password=password dbname=postgres sslmode=disable
    networks:
      database_database:

networks:
  database_database:
    external: true
