version: '3'

services:
  api:
    build: ./
    ports:
    - 8080:8080
    environment:
      - PORT=8080
      - DB_HOST=scylla-node1,scylla-node2,scylla-node3
    networks:
      database_database:

networks:
  database_database:
    external: true
