version: '3'

services:
  api:
    build: ./
    ports:
    - 8080:8080
    environment:
      - PORT=8080
      - DB_CONNECTION_STRING=host=postgres port=5432 user=postgres password=password dbname=postgres sslmode=disable
      - AUTH_WEBHOOK_JWT_SECRET=c5e54bc64d851d34efdf9ad052f5cb38e2f83fce89a8594c9205a5e6618b2ca4
      - AUTH_JWKS_URI=https://mappichat-staging.us.auth0.com/.well-known/jwks.json
    networks:
      postgres_database:

networks:
  postgres_database:
    external: true
