version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    networks:
      database:
    volumes:
      - postgres-vol:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      database:

networks:
  database:
    driver: bridge

volumes:
  postgres-vol: